name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/setup-node

      - name: Lint ✅
        run: yarn lint

  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/setup-node

      - name: Cache Turborepo artifacts ⚡
        uses: actions/cache@v4
        with:
          path: .turbo/cache
          key: turbo-check-data-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-check-data-${{ runner.os }}-

      - name: JSON Schema 💽
        run: yarn check-data

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/setup-node

      - name: Vitest 🧪
        run: yarn test

      - uses: codecov/codecov-action@v5
