name: lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/setup-node

      - name: Lint ✅
        run: npm run lint

      - name: Prettier 💅
        run: npm run check-code

      - name: JSON Schema 💽
        run: npm run check-data
